name: FF Tool CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us_east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          AWS_REGION: us_east-1
          ECR_REPO_URI: 905418110363.dkr.ecr.us-east-1.amazonaws.com/aws-deploy
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          docker push $ECR_REPO_URI:$IMAGE_TAG

      - name: Update ECS service
        env:
          AWS_REGION: us_east-1
          CLUSTER_NAME: FFTool-From-Template
          SERVICE_NAME: ff-tool-from-template
          ECR_REPO_URI: 905418110363.dkr.ecr.us-east-1.amazonaws.com/aws-deploy:${{ github.sha }}
          IMAGE_TAG: latest
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --output json